# src/modules/type.gql

type User {
  id: ID!
  name: String!
  email: String!
  posts: [Post!]!
}

type Post {
  id: ID!
  title: String!
  content: String!
  authorId: ID! # Relationship, not authorId
  comments: [Comment!]!
  createdAt: String
}

type Comment {
  id: ID!
  text: String!
  author: User!
  postId: String!
}

# custom error(ass-2.5)
type Error{
  code: Int!
  message: String!
}